version: '3'

services:
  db:
    image: mysql
    container_name: extensemanager-db
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root-passowrd
      MYSQL_DATABASE: expensemanager
      MYSQL_USER: expensemanager
      MYSQL_PASSWORD: expensemanager
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: