version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: expensemanager_db
    restart: always
    environment:
      POSTGRES_USER: expensemanager
      POSTGRES_PASSWORD: expensemanager
      POSTGRES_DB: expensemanager
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    container_name: expensemanager_api
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expensemanager
      - SPRING_DATASOURCE_USERNAME=expensemanager
      - SPRING_DATASOURCE_PASSWORD=expensemanager
    depends_on:
      - db

volumes:
  db_data: