version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: expensemanager_db
    restart: always
    environment:
      POSTGRES_USER: expensemanager
      POSTGRES_PASSWORD: expensemanager
      POSTGRES_DB: expensemanager
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: