cors:
  originPatterns: http://localhost:3000,http:localhost:8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://expensemanager_db:5432/expensemanager
    username: expensemanager
    password: expensemanager
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        type:
          trace-level: TRACE
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE